# Generated by Django 5.0.6 on 2024-06-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_author_genre_books"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
